### ISSUE TITLE
Key not found error when listing config of partially formed project.json

### ISSUE THREAD

**Issue by eduardolundgren** [launchpad-project/cli#9]
```
~/P/awesome ❯❯❯ cat project.json                                                                                    ⏎ personal ✚ ✖ ✱ ◼
{
    "name": "Awesome",
    "description": "",
    "id": "awesome",
    "ownerId": "",
    "url": "",
    "users": null
}%                                                                                                                                     ~/P/awesome ❯❯❯ launchpad config -l                                                                                   personal ✚ ✖ ✱ ◼
id = awesome
name = Awesome
description = 
panic: key not found

goroutine 1 [running]:
github.com/launchpad-project/cli/configstore.(*Store).GetRequiredString(0xc8200744c0, 0x46e848, 0x6, 0x0, 0x0)
	/Users/eduardo/gocode/src/github.com/launchpad-project/cli/configstore/configstore.go:90 +0x9e
github.com/launchpad-project/cli/configstore.(*Store).List(0xc8200744c0)
	/Users/eduardo/gocode/src/github.com/launchpad-project/cli/configstore/configstore.go:128 +0xcf
github.com/launchpad-project/cli/cmd/config.configRun(0x67e160, 0xc8200773b0, 0x0, 0x1)
	/Users/eduardo/gocode/src/github.com/launchpad-project/cli/cmd/config/config.go:45 +0x1a3
github.com/spf13/cobra.(*Command).execute(0x67e160, 0xc820077330, 0x1, 0x1, 0x0, 0x0)
	/Users/eduardo/gocode/src/github.com/spf13/cobra/command.go:565 +0x869
github.com/spf13/cobra.(*Command).ExecuteC(0x67db60, 0x67e160, 0x0, 0x0)
	/Users/eduardo/gocode/src/github.com/spf13/cobra/command.go:651 +0x56b
github.com/spf13/cobra.(*Command).Execute(0x67db60, 0x0, 0x0)
	/Users/eduardo/gocode/src/github.com/spf13/cobra/command.go:610 +0x2d
github.com/launchpad-project/cli/cmd.Execute()
	/Users/eduardo/gocode/src/github.com/launchpad-project/cli/cmd/root.go:54 +0x23
main.main()
	/Users/eduardo/gocode/src/github.com/launchpad-project/cli/main.go:13 +0x14

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/asm_amd64.s:1696 +0x1

goroutine 19 [syscall]:
os/signal.loop()
	/usr/local/Cellar/go/1.5.1/libexec/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/Cellar/go/1.5.1/libexec/src/os/signal/signal_unix.go:28 +0x37
~/P/awesome ❯❯❯ 
```

**Comment by henvic** [comment]
`launchpad config` doesn't exist anymore.
